### ISSUE TITLE
math - A new function isclose() provides a way to test for approximate equality.

### ISSUE THREAD

**Issue by Leah1115** [ECE595/micropython#6]
A new function isclose() provides a way to test for approximate equality.

https://docs.python.org/3/whatsnew/3.5.html#math

https://github.com/micropython/micropython/blob/master/docs/differences/python_35.rst

**Comment by jbbjarnason** [comment]
Fixed here: https://github.com/micropython/micropython/commit/af5c998f37ddc62abfd36e0b8be511c392fc25d8
